create table public.citi - bike - monthly (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  h3_cell_start character varying null,
  h3_cell_end character varying null,
  date_month date null,
  count integer null default 0,
  constraint citi - bike - monthly_pkey primary key (id),
  constraint unique_by_month unique (h3_cell_start, h3_cell_end, date_month)
) TABLESPACE pg_default;

create index IF not exists idx_citi_bike_monthly_date_cells on public."citi-bike-monthly" using btree (date_month, h3_cell_start, h3_cell_end) TABLESPACE pg_default;

create index IF not exists idx_citi_bike_end_cell_date on public."citi-bike-monthly" using btree (h3_cell_end, date_month) INCLUDE (h3_cell_start, count) TABLESPACE pg_default;

create index IF not exists idx_citi_bike_start_cell_date on public."citi-bike-monthly" using btree (h3_cell_start, date_month) INCLUDE (h3_cell_end, count) TABLESPACE pg_default;

create index IF not exists idx_citi_bike_date_end on public."citi-bike-monthly" using btree (date_month, h3_cell_end) INCLUDE (count) TABLESPACE pg_default;

create index IF not exists idx_citi_bike_date_start on public."citi-bike-monthly" using btree (date_month, h3_cell_start) INCLUDE (count) TABLESPACE pg_default;// app/api/trips/route.ts
export const revalidate = 86400 // Cache for 24 hours

export async function GET() {
  const response = await fetch(
    `${process.env.NEXT_PUBLIC_SUPABASE_URL}/rest/v1/rpc/get_monthly_totals`,
    {
      headers: {
        'apikey': process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
        'Authorization': `Bearer ${process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY}`,
      },
      next: { revalidate: 86400 } // Cache for 24 hours
    }
  )
  
  const data = await response.json()
  return Response.json(data)
}